# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [2]:
import os
os.chdir("/Users/sampathkumar/Desktop")
import pandas as p
required = p.read_csv("ccp_current_csv.csv")
print (required)


                 STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW        

In [79]:
from numpy import genfromtxt
#required = genfromtxt('ccp_current_csv.csv', delimiter=',')
genfromtxt(fname = required, dtype = ('str'))
print (required)

TypeError: must be str or None, not bytes

### 3.1.a  what is its shape and what does that mean?

In [8]:
required.shape

(465, 27)

The shape basically represents the number of rows and columns that are present in the given file. 

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [12]:
required['QUADRANT'].value_counts()
#This function returns the number of times each column value is repeated in the dataset.

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

In [69]:
#We can find unique values that occur in the column first and then find the occurance or count of each value in the coulmn.
print (required['QUADRANT'].unique())
print (required.index[required['QUADRANT']=='NE'].shape)
print (required.index[required['QUADRANT']=='NW'].shape)
print (required.index[required['QUADRANT']=='SE'].shape)
print (required.index[required['QUADRANT']=='BN'].shape)
print (required.index[required['QUADRANT']=='SW'].shape)

['NW' 'NE' 'SE' 'SW' 'BN']
(163,)
(195,)
(84,)
(12,)
(11,)


## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [55]:
import numpy as np
a = np.array([1,2,3,4],dtype=np.float)
b = np.array([5,6,7,8],dtype=np.float)
c = np.add(a,b)
print (c) 
c =a+b
print (c)

[  6.   8.  10.  12.]
[  6.   8.  10.  12.]


### 3.3.2 subtraction a-b

In [57]:
c = np.subtract(a,b)
print (c)
c =a-b
print (c)

[-4. -4. -4. -4.]
[-4. -4. -4. -4.]


### 3.3.3 multiplication a*b

In [59]:
c = np.multiply(a,b)
print (c)
c = a*b
print (c)

[  5.  12.  21.  32.]
[  5.  12.  21.  32.]


### 3.3.4 divsion a/b

In [60]:
c = np.divide(a,b)
print (c)
c = a/b
print (c)

[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]


### 3.3.5 modulo  a%b

In [61]:
c =np.mod(a,b)
print (c)
c =a%b
print (c)

[ 1.  2.  3.  4.]
[ 1.  2.  3.  4.]


### 3.3.6 power  a^b

In [63]:
c = np.power(a,b)
print (c)
c = a**b
print (c)

[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


## Homework 3.4
Find your own data and load it into a dataframe

I found a dataset which contains nearly 6000 cricket matches. Each phase of the game is called an innings. While a team bats the other team fields and there are 11 players in a team. The team which scores most runs in an innings wins the match. The fielding teams bowls an over which consists of 6 balls. The team which wins can either win by runs or win by wickets. Win by runs happens when the team which bats first wins and win by wickets happens when the team which bats second wins. The dataset is of t20 matches where the fielding team bowls 20 overs. 

In [100]:
import pandas as p
required = p.read_csv("t20_matches.csv")
print (required)
required.shape

                                          match_details  \
0     North Group:Durham v Nottinghamshire at Cheste...   
1     South Group:Hampshire v Sussex at Southampton-...   
2     Midlands/Wales/West Group:Somerset v Warwicksh...   
3     South Group:Surrey v Middlesex at The Oval- Ju...   
4     Midlands/Wales/West Group:Worcestershire v Nor...   
5     Midlands/Wales/West Group:Gloucestershire v Wo...   
6     South Group:Surrey v Essex at East Molesey- Ju...   
7     North Group:Yorkshire v Derbyshire at Leeds- J...   
8     Midlands/Wales/West Group:Glamorgan v Northamp...   
9     South Group:Kent v Hampshire at Beckenham- Jun...   
10    North Group:Leicestershire v Yorkshire at Leic...   
11    North Group:Nottinghamshire v Lancashire at No...   
12    South Group:Surrey v Sussex at East Molesey- J...   
13    North Group:Durham v Leicestershire at Chester...   
14    Midlands/Wales/West Group:Glamorgan v Somerset...   
15    South Group:Hampshire v Essex at Southampton- ... 

(6417, 24)

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [132]:
print (required.describe())

#This function returns the values such as count, mean, minimum value, maximum value and standard deviation for any values which are either int or float.
#In case we want to find the mean, min or max value we can use independent function which can be applied on a particular column.
print (required['innings1_runs'].max())
#The above function returns the most number of runs scored by a team which bats first
print (required['innings2_runs'].max())
#The above function returns the most number of runs scored by a team which bats second
print (required["win_by_runs"].max())
#The above function gives the number of runs the first team beat the second team by
print (required["win_by_runs"].std())
#Returns the standard deviation 
print (required['balls_remaining'].max())
#This returns the maximum value where the team which bats second chased the score posed by the first team with balls to spare

       win_by_runs  win_by_wickets  balls_remaining  innings1_runs  \
count  2931.000000     3004.000000      2969.000000    6151.000000   
mean     31.320710        6.089214        13.978107     151.409527   
std      26.838237        1.996341        14.664918      32.986924   
min       1.000000        1.000000         0.000000       1.000000   
25%      11.000000        5.000000         4.000000     131.000000   
50%      24.000000        6.000000         9.000000     152.000000   
75%      45.000000        8.000000        19.000000     173.000000   
max     172.000000       10.000000       100.000000     263.000000   

       innings1_wickets  innings1_overs_batted  innings1_overs  innings2_runs  \
count       6151.000000            6151.000000     6151.000000    6070.000000   
mean           6.577630              19.523199       19.738612     136.125371   
std            2.152355               1.924720        1.510632      31.880776   
min            0.000000               0.20000

In [120]:
print (required.loc[required['innings1_runs']>required['innings2_runs']])
#This returns the list of matches where the team which bats first wins

                                          match_details  \
1     South Group:Hampshire v Sussex at Southampton-...   
2     Midlands/Wales/West Group:Somerset v Warwicksh...   
6     South Group:Surrey v Essex at East Molesey- Ju...   
7     North Group:Yorkshire v Derbyshire at Leeds- J...   
8     Midlands/Wales/West Group:Glamorgan v Northamp...   
10    North Group:Leicestershire v Yorkshire at Leic...   
13    North Group:Durham v Leicestershire at Chester...   
15    South Group:Hampshire v Essex at Southampton- ...   
16    Midlands/Wales/West Group:Worcestershire v War...   
17    South Group:Sussex v Middlesex at Hove- Jun 18...   
22    North Group:Leicestershire v Lancashire at Lei...   
23    Midlands/Wales/West Group:Northamptonshire v S...   
24    Midlands/Wales/West Group:Warwickshire v Glamo...   
25    North Group:Yorkshire v Durham at Leeds- Jun 2...   
30     South Group:Sussex v Essex at Hove- Jun 21, 2003   
31    North Group:Derbyshire v Durham at Derby- Jun ... 

In [118]:
print (required["win_by_runs"].median())
#This returns the median which is basically the middle most value

24.0


In [121]:
print (required.loc[required['innings2_runs']>required['innings1_runs']])
#This returns the details of the macthes where the team which chases a total wins.

                                          match_details  \
0     North Group:Durham v Nottinghamshire at Cheste...   
3     South Group:Surrey v Middlesex at The Oval- Ju...   
4     Midlands/Wales/West Group:Worcestershire v Nor...   
5     Midlands/Wales/West Group:Gloucestershire v Wo...   
9     South Group:Kent v Hampshire at Beckenham- Jun...   
11    North Group:Nottinghamshire v Lancashire at No...   
12    South Group:Surrey v Sussex at East Molesey- J...   
14    Midlands/Wales/West Group:Glamorgan v Somerset...   
18    North Group:Derbyshire v Nottinghamshire at De...   
19    Midlands/Wales/West Group:Gloucestershire v No...   
20    North Group:Lancashire v Yorkshire at Manchest...   
21    South Group:Middlesex v Kent at Richmond- Jun ...   
26    South Group:Essex v Kent at Chelmsford- Jun 20...   
27    North Group:Lancashire v Derbyshire at Manches...   
28    North Group:Nottinghamshire v Leicestershire a...   
29    Midlands/Wales/West Group:Somerset v Glouceste... 

In [93]:
print (required.loc[required['innings1_runs']==263])
#We can use this function to determine the details of the match where highest total was posed which was a couple of times. 

                                          match_details  \
3717  31st match:Royal Challengers Bangalore v Pune ...   
6077  1st T20I:Sri Lanka v Australia at Pallekele- S...   

                                           result  \
3717  Royal Challengers Bangalore won by 130 runs   
6077                     Australia won by 85 runs   

                                                 scores      date      venue  \
3717  Royal Challengers Bangalore 263/5 (20/20 ov); ...  23/04/13  Bangalore   
6077  Australia 263/3 (20/20 ov); Sri Lanka 178/9 (2...  06/09/16  Pallekele   

           round                         home           away  \
3717  31st match  Royal Challengers Bangalore  Pune Warriors   
6077    1st T20I                    Sri Lanka      Australia   

                           winner  win_by_runs   ...    innings1_wickets  \
3717  Royal Challengers Bangalore        130.0   ...                 5.0   
6077                    Australia         85.0   ...                 3.0   


In [115]:
print (required['date'].value_counts())
# This returns the number of matches played on each date. If we wanted to find the maximum value played on a particlar date we can use the below function
required['date'].value_counts().max()

06/01/16    16
17/07/15    15
17/03/13    14
10/01/16    14
07/01/16    14
02/01/16    14
25/05/09    13
03/01/16    13
29/01/17    13
19/03/13    13
22/03/13    13
04/04/14    13
10/07/15    13
21/03/13    13
04/01/16    13
03/04/07    12
28/03/15    12
04/04/07    12
27/03/15    12
26/03/12    12
07/04/07    12
21/10/11    12
02/04/14    12
01/04/14    12
18/03/13    12
20/10/11    12
25/03/15    12
30/03/12    12
27/03/12    12
03/07/15    11
            ..
28/12/10     1
16/08/15     1
05/11/08     1
24/09/12     1
18/09/11     1
06/06/10     1
23/05/12     1
22/12/11     1
01/07/13     1
26/04/11     1
29/04/08     1
24/05/16     1
23/03/07     1
25/10/08     1
01/10/16     1
09/08/13     1
22/08/13     1
06/05/16     1
28/08/12     1
13/12/16     1
01/12/06     1
09/11/15     1
20/05/11     1
16/02/11     1
19/10/09     1
22/05/09     1
29/04/15     1
26/04/12     1
20/02/11     1
10/02/09     1
Name: date, Length: 2273, dtype: int64


16

In [116]:
required['winner'].value_counts()
# This returns the team which won the most number of t20 matches. In this case the number of matches abondoned without bowling a ball was the maximum.

Match abandoned without a ball bowled    209
No result                                110
Chennai Super Kings                       94
Mumbai Indians                            91
Lancashire                                90
Hampshire                                 88
Warwickshire                              85
Nottinghamshire                           84
Essex                                     82
Surrey                                    82
Somerset                                  80
Kolkata Knight Riders                     78
Royal Challengers Bangalore               77
Kent                                      77
Sussex                                    74
Leicestershire                            73
Titans                                    71
Northamptonshire                          71
Pakistan                                  69
Yorkshire                                 69
Rajasthan Royals                          69
Auckland                                  68
Kings XI P

In [127]:
required2 = required.loc[required['innings2_overs_batted']==20]
#print (required2)
#print (required2.loc[required2['win_by_runs']])
required2['win_by_runs'].value_counts()
#This returns the value where the team although batted second for complete 20 overs could not chase the total. For example the team batted second for 20 overs and lost by one run. This happend 80 times. 

1.0      80
4.0      67
2.0      63
14.0     63
10.0     59
3.0      58
8.0      56
9.0      56
6.0      56
15.0     55
5.0      52
11.0     52
19.0     51
7.0      47
12.0     45
17.0     41
16.0     38
18.0     38
13.0     37
21.0     35
22.0     34
23.0     33
24.0     32
25.0     30
35.0     26
29.0     25
20.0     24
37.0     22
34.0     21
27.0     21
         ..
66.0      3
69.0      3
84.0      3
65.0      3
71.0      3
85.0      3
59.0      3
101.0     2
83.0      2
79.0      2
105.0     2
97.0      2
70.0      2
87.0      1
95.0      1
130.0     1
91.0      1
89.0      1
81.0      1
75.0      1
86.0      1
111.0     1
73.0      1
142.0     1
82.0      1
92.0      1
118.0     1
148.0     1
60.0      1
119.0     1
Name: win_by_runs, Length: 99, dtype: int64

In [129]:
print (required['venue'].value_counts())
#This returns the number of matches that happened at each venue. We can use max function to find max number of matches ar a particular venue. 
print (required['venue'].value_counts().max())

Dhaka                  176
Lahore                 167
Karachi                156
Delhi                  130
Mumbai                 119
Durban                 118
Birmingham             104
Johannesburg           100
Nottingham              98
Colombo (RPS)           97
The Oval                97
Harare                  96
Dubai (DSC)             92
Kolkata                 92
Chennai                 89
Bangalore               89
Cape Town               89
Abu Dhabi               88
Leicester               87
Southampton             87
Centurion               87
Rawalpindi              85
Hyderabad (Deccan)      85
Manchester              81
Cardiff                 81
Chester-le-Street       79
Chelmsford              77
Jaipur                  76
Taunton                 75
Hove                    73
                      ... 
Kandy                    2
Kidderminster            2
Mong Kok                 2
East Molesey             2
Aberdeen                 2
Rugby                    1
C

In [130]:
required.loc[required['innings2_runs']==required['innings1_runs']]
#This returns the number of matches that ended in a tie where 1st innings total = 2nd innings total.

match_details  \
104   Midland/Wales/West Group:Gloucestershire v War...   
179   Midland/Wales/West Group:Glamorgan v Somerset ...   
264   Group B:Colts Cricket Club v Kurunegala Youth ...   
319   Only T20I:New Zealand v West Indies at Aucklan...   
352   Pool A:Karachi Zebras v Peshawar Panthers at K...   
359   Pool A:Karachi Zebras v Multan Tigers at Karac...   
397   Northamptonshire v Somerset at Northampton- Ju...   
559   Group B:Bloomfield Cricket and Athletic Club v...   
635   West Zone:Gujarat v Saurashtra at Mumbai- Apr ...   
679   South Division:Hampshire v Kent at Southampton...   
765   10th Match, Group D:India v Pakistan at Durban...   
811     Auckland v Canterbury at Auckland- Jan 23, 2008   
865         Eagles v Lions at Bloemfontein- Apr 4, 2008   
968   Midlands/West/Wales Division:Gloucestershire v...   
1018  North Division:Yorkshire v Durham at Leeds- Ju...   
1034  South Division:Hampshire v Essex at Southampto...   
1088  3rd Match:Canada v Zimbabwe at King City (NW)-...   
1101  1st T20I:New Zealand v West Indies at Auckland...   
1134  Lions v Cape Cobras at Potchefstroom- Feb 4, 2009   
1144  Semi-Final - 3rd Leg:Dolphins v Cape Cobras at...   
1145  Semi-Final - 3rd Leg:Warriors v Eagles at Port...   
1166  Northern Districts v Canterbury at Hamilton- F...   
1199      Centrals v Westerns at Bulawayo- May 13, 2009   
1202  Northerns (Zimbabwe) v Westerns at Bulawayo- M...   
1220  10th match:Kolkata Knight Riders v Rajasthan R...   
1430  11th Match, Group B:Eagles v Sussex at Delhi- ...   
1493         Auckland v Otago at Auckland- Jan 26, 2010   
1499  2nd Match:Scotland v Uganda at Nairobi (Gym)- ...   
1550  2nd T20I:New Zealand v Australia at Christchur...   
1710  16th match:Chennai Super Kings v Kings XI Punj...   
...                                                 ...   
4114  Central Districts v Auckland at New Plymouth- ...   
4153  Sydney Sixers v Perth Scorchers at Sydney- Jan...   
4181  Warriors v Dolphins at Port Elizabeth- Jan 17,...   
4183      Warriors v Lions at East London- Jan 19, 2014   
4395  North Zone:Punjab v Jammu & Kashmir at Mohali-...   
4437  19th match:Kolkata Knight Riders v Rajasthan R...   
4499  5th Match:Guyana Amazon Warriors v Trinidad & ...   
4570  South Division:Glamorgan v Kent at Cardiff- Ju...   
4672  Group B:Karachi Zebras v Rawalpindi Rams at Ka...   
4712  12th Match, Group B:Barbados Tridents v Cape C...   
4776      Lions v Knights at Potchefstroom- Nov 9, 2014   
4788       Titans v Warriors at Centurion- Nov 23, 2014   
4820  Melbourne Stars v Sydney Sixers at Melbourne- ...   
4852  Easterns v South Western Districts at Benoni- ...   
4912  North Zone:Delhi v Services at Delhi- Mar 28, ...   
4966  Group A:Badureliya Sports Club v Ragama Cricke...   
5026  18th match:Rajasthan Royals v Kings XI Punjab ...   
5244  North Group:Leicestershire v Yorkshire at Leic...   
5302  4th Quarter-Final:Kent v Lancashire at Canterb...   
5332  Group A:Bahawalpur Region v Hyderabad Region a...   
5401  3rd T20I:England v Pakistan at Sharjah- Nov 30...   
5402       Warriors v Knights at Cape Town- Nov 1, 2015   
5404      Cape Cobras v Lions at Cape Town- Nov 1, 2015   
5445    Auckland v Canterbury at Auckland- Nov 18, 2015   
5505  5th unofficial T20I:England Lions v Pakistan A...   
5725  Final:Mountaineers v Mashonaland Eagles at Bul...   
6138  2nd Semi-Final:Northern Cape v North West at O...   
6227  Canterbury v Wellington at Christchurch- Dec 1...   
6249      Wellington v Otago at Wellington- Jan 3, 2017   
6307  2nd Semi-Final:Brisbane Heat v Sydney Sixers a...   

                                                 result  \
104               Warwickshire won (lost fewer wickets)   
179                  Glamorgan won (lost fewer wickets)   
264                                          Match tied   
319           Match tied (New Zealand won the bowl-out)   
352             Karachi Zebras won (lost fewer wickets)   
359   Multan Tigers won on fa